#1 updated my data base
osadolortech/blogapi pull request #1
Opened 2022-06-02 23:28 UTC by osadolortech

2022-06-02 23:33 UTC, iamr0b0tx requested changes

2022-06-02 23:33 UTC, iamr0b0tx commented on config/database.py
> +client = MongoClient("mongodb+srv://FinalBlog :Computer333@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
use env variables

2022-06-03 00:12 UTC, osadolortech commented on config/database.py
> +client = MongoClient("mongodb+srv://FinalBlog :Computer333@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
changes done sir

2022-06-03 00:13 UTC, osadolortech commented on config/database.py
> +client = MongoClient("mongodb+srv://FinalBlog :Computer333@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
changes done sir

2022-06-03 00:15 UTC, osadolortech commented on config/database.py
> +client = MongoClient("mongodb+srv://FinalBlog :Computer333@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
changes done sir

2022-06-03 09:34 UTC, osadolortech reviewed
changes made

2022-06-03 11:03 UTC, iamr0b0tx requested changes

2022-06-03 11:03 UTC, iamr0b0tx commented on config/database.py
> +client = MongoClient("mongodb+srv://username:password@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
why not just make the entire database URL an ENV Variable

2022-06-03 15:14 UTC, osadolortech commented on config/database.py
> +client = MongoClient("mongodb+srv://username:password@cluster0.ve2nnja.mongodb.net/mainblog?retryWrites=true&w=majority")
please sir check if the new update is fine now

2022-06-03 15:33 UTC, merged